use custBehavior;

select * from mycustomer;

#1. Total revenue generated by male and female customer.
select gender, SUM(purchase_amount) as revenue
from mycustomer
group by gender

#2. Customer that used discount but still spend more than the average purchase amount.
select customer_id, purchase_amount
from mycustomer
where discount_applied='Yes' and purchase_amount>=
(select Avg(purchase_amount) from mycustomer)

#3. which are the top 5 products with the highest average review rating
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from mycustomer
group by item_purchased 
order by avg(review_rating) desc
limit 5

#4. compare the average Purchase accounts between standard and express shipping
 select shipping_type, round(avg(purchase_amount),2)
 from mycustomer
 where shipping_type IN ('Standard','Express')
 group by shipping_type
 
 #5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and no-subscribers
 select subscription_status,
 count(customer_id) as 'TotalCustomer', avg(purchase_amount) as avg_spend, sum(purchase_amount) as total_revenue
 from mycustomer
 group by subscription_status
 order by total_revenue, avg_spend desc
 
 #6 which 5 product have the highest percentage of purchases with discount applied
 select item_purchased, 
 round(sum(case when discount_applied='yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
 from mycustomer
 group by item_purchased
 order by discount_rate desc 
 limit 5
 
 
 
 